webnode/article/urls.py
from django.urls import path
from article import views


app_name = 'article'
urlpatterns = [
    path('', views.article, name='article'),
]

webnode/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
]

webnode/webnode/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),
]

webnode/article/models.py
from django.db import models

# Create your models here.

webnode/main/models.py
from django.db import models

# Create your models here.

webnode/article/views.py
from django.shortcuts import render

def article(request):
    '''
    Render the article page
    '''
    return render(request, 'article/article.html')

webnode/main/views.py
from django.shortcuts import render


def main(request):
    '''
    Render the main page
    '''
    context = {'like':'我們的服務技術,協助您快速架設網站'}
    return render(request, 'main/main.html', context)

def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

webnode/article/templates/article/article.html
{% extends 'main/base.html' %}
{% block content %}
<p><h1><center>理想的網站及網路商城</h1></p>
<p>上百種的新潮樣式，絕對能符合您個人需求，為您設立個人網站，公司企業網站及網路商城的最佳選擇。</p>
{% endblock %}

webnode/main/templates/main/about.html
{% extends 'main/base.html' %}
{% block heading %}關於{% endblock %}
{% block content %}
<p><h1><center>免費又簡單的網站設立工具</h1></p>
<p>一個快速且容易的網站架設工具，在網路上設計網站十分的簡單又免費。此外，您也可以使用自己的網域名稱。</p>
{% endblock %}

webnode/main/templates/main/base.html
<!doctype html>
{% load static %}
<html>
<head>
<title> 期末作業 </title>
<meta charset="utf-8">
<p> <img src="{% static 'main/img/webnode.png' %}"> </p>
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
{% block content %}{% endblock %}
</body>
</html>

webnode/main/templates/main/main.html
{% extends 'main/base.html' %}
{% block content %}
<p>{{ like }}</p>
{% endblock %}

webnode/main/templates/main/menu.html
<ul id="menu">
  <li><a href="{% url 'main:main' %}">首頁</a></li>
  <li><a href="{% url 'main:about' %}">個人網站</a></li>
  <li><a href="{% url 'article:article' %}">企業網站</a></li>
</ul>